name: AIDE-Plus Build

on:
  push:
    branches: [ master, 2.3 ]
  pull_request:
    branches: [ master, 2.3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        local-cache: true

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 添加 Gradle Wrapper
    - name: Setup Gradle Wrapper
      run: |
        gradle wrapper
        chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        if [ -f "build.gradle" ]; then
          ./gradlew assembleDebug
        elif [ -f "app_rewrite/build.gradle" ]; then
          cd app_rewrite
          ../gradlew assembleDebug
        fi
      
    - name: Run Tests
      run: |
        if [ -f "build.gradle" ]; then
          ./gradlew test
        elif [ -f "app_rewrite/build.gradle" ]; then
          cd app_rewrite
          ../gradlew test
        fi
      
    - name: Build Native Libraries
      run: |
        if [ -d "native/EnsureCapacity" ]; then
          cd native/EnsureCapacity
          cmake .
          make
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: |
          app_rewrite/build/outputs/apk/debug/*.apk
          */build/outputs/apk/debug/*.apk
        if-no-files-found: warn
        
    - name: Upload Native Libraries
      uses: actions/upload-artifact@v3
      with:
        name: native-libs
        path: |
          native/EnsureCapacity/build/*.so
          */build/*.so
        if-no-files-found: warn
