name: AIDE-Plus Build

on:
  push:
    branches: [ master, 2.3 ]
  pull_request:
    branches: [ master, 2.3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android SDK Components
      run: |
        echo "Installing Android SDK components..."
        yes | sdkmanager --licenses
        sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "extras;android;m2repository" \
          "extras;google;m2repository"
        
        echo "Installed packages:"
        sdkmanager --list_installed

    - name: Setup Gradle
      run: |
        # 创建local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        
        # 下载并安装Gradle
        wget https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
        unzip gradle-7.3.3-bin.zip
        export PATH=$PATH:$PWD/gradle-7.3.3/bin
        
        # 生成Gradle Wrapper
        gradle wrapper
        chmod +x gradlew

    - name: Debug Project Structure
      run: |
        echo "Project root contents:"
        ls -la
        
        echo "\nGradle files:"
        find . -name "*.gradle" -type f -exec sh -c 'echo "=== {} ==="; cat "{}"' \;
        
        echo "\nLocal properties:"
        cat local.properties || echo "No local.properties found"
        
        echo "\nAndroid SDK location:"
        echo $ANDROID_SDK_ROOT
        ls -la $ANDROID_SDK_ROOT/platforms
        ls -la $ANDROID_SDK_ROOT/build-tools

    - name: Build APK
      run: |
        # 尝试直接构建
        echo "Attempting direct build..."
        ./gradlew assembleDebug --info || true
        
        # 如果直接构建失败，尝试查找并构建主模块
        if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "Direct build failed, searching for main module..."
          
          # 查找包含android应用插件的build.gradle文件
          MAIN_GRADLE=$(find . -type f -name "build.gradle" -exec grep -l "com.android.application" {} \; | head -n 1)
          
          if [ ! -z "$MAIN_GRADLE" ]; then
            MODULE_DIR=$(dirname "$MAIN_GRADLE")
            MODULE_NAME=$(basename "$MODULE_DIR")
            echo "Found main module: $MODULE_NAME in $MODULE_DIR"
            
            echo "Building module $MODULE_NAME..."
            ./gradlew :$MODULE_NAME:assembleDebug --info
            
            echo "Build outputs:"
            find "$MODULE_DIR/build/outputs" -type f -ls || true
          else
            echo "No Android application module found"
            echo "All gradle files:"
            find . -name "*.gradle" -type f -exec echo {} \;
          fi
        fi
        
        echo "Looking for APK files:"
        find . -name "*.apk" -type f -ls

    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/build/outputs/apk/**/*.apk
          **/build/reports/**
          **/build/outputs/**
          **/*.gradle
          local.properties
        if-no-files-found: warn
