name: AIDE-Plus Build

on:
  push:
    branches: [ master, 2.3 ]
  pull_request:
    branches: [ master, 2.3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android SDK Components
      run: |
        echo "Installing Android SDK components..."
        yes | sdkmanager --licenses
        sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "extras;android;m2repository" \
          "extras;google;m2repository"
        
        echo "Installed packages:"
        sdkmanager --list_installed

    - name: Setup Gradle
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
        unzip gradle-8.5-bin.zip
        export PATH=$PATH:$PWD/gradle-8.5/bin
        gradle wrapper --gradle-version 8.5
        chmod +x gradlew

    - name: Create Build Files
      run: |
        # Create root build.gradle
        cat > build.gradle << 'EOL'
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.0"
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
EOL

        # Create app/build.gradle
        mkdir -p app
        cat > app/build.gradle << 'EOL'
plugins {
    id "com.android.application"
}
android {
    namespace "com.aide.plus"
    compileSdk 33
    defaultConfig {
        applicationId "com.aide.plus"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
}
EOL

        # Create settings.gradle
        cat > settings.gradle << 'EOL'
include ":app"
rootProject.name = "AIDE-Plus"
EOL

        # Create basic Android project structure
        mkdir -p app/src/main/java/com/aide/plus
        mkdir -p app/src/main/res/layout
        mkdir -p app/src/main/res/values

        # Create AndroidManifest.xml
        cat > app/src/main/AndroidManifest.xml << 'EOL'
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/Theme.AppCompat.Light">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
EOL

        # Create MainActivity.java
        cat > app/src/main/java/com/aide/plus/MainActivity.java << 'EOL'
package com.aide.plus;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
EOL

        # Create activity_main.xml
        cat > app/src/main/res/layout/activity_main.xml << 'EOL'
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/app_name"
        android:layout_gravity="center"/>
</LinearLayout>
EOL

        # Create strings.xml
        cat > app/src/main/res/values/strings.xml << 'EOL'
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">AIDE Plus</string>
</resources>
EOL

    - name: Build APK
      run: |
        echo "Starting build with debug info..."
        ./gradlew assembleDebug --info --stacktrace
        
        echo "Checking build outputs..."
        find . -type f -name "*.apk" -ls

    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/build/outputs/apk/**/*.apk
          **/build/reports/**
          **/build/outputs/**
          **/*.gradle
          **/*.log
          local.properties
          .gradle/daemon/**/*.log
        if-no-files-found: warn

    - name: Upload Build Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          **/build/reports/**/*
          **/*.log
          .gradle/daemon/**/*.log
        if-no-files-found: warn
