name: AIDE-Plus Build

on:
  push:
    branches: [ master, 2.3 ]
  pull_request:
    branches: [ master, 2.3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-platform: '33'
        build-tools: '33.0.0'
        
    - name: Setup Gradle
      run: |
        # 下载并安装Gradle
        wget https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
        unzip gradle-7.3.3-bin.zip
        export PATH=$PATH:$PWD/gradle-7.3.3/bin
        
        # 生成Gradle Wrapper
        gradle wrapper
        chmod +x gradlew
        ./gradlew --version

    - name: Build APK
      run: |
        echo "Starting APK build process..."
        # 显示项目结构
        ls -la
        
        # 检查并显示build.gradle内容
        if [ -f "build.gradle" ]; then
          echo "Root build.gradle contents:"
          cat build.gradle
        fi
        
        # 检查并显示app/build.gradle内容
        if [ -f "app/build.gradle" ]; then
          echo "App build.gradle contents:"
          cat app/build.gradle
        fi
        
        # 尝试构建APK
        echo "Building debug APK..."
        ./gradlew assembleDebug --stacktrace
        
        echo "Building release APK..."
        ./gradlew assembleRelease --stacktrace
        
        # 显示构建产物
        echo "Build outputs:"
        find . -name "*.apk"

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: |
          app/build/outputs/apk/debug/*.apk
          */build/outputs/apk/debug/*.apk
        if-no-files-found: warn
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: |
          app/build/outputs/apk/release/*.apk
          */build/outputs/apk/release/*.apk
        if-no-files-found: warn

    - name: Upload Build Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          app/build/reports/**/*
          */build/reports/**/*
        if-no-files-found: warn
