name: AIDE-Plus Build

on:
  push:
    branches: [ master, 2.3 ]
  pull_request:
    branches: [ master, 2.3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        local-cache: true

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: List Project Structure
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Finding Gradle files:"
        find . -name "build.gradle" -o -name "settings.gradle"
        echo "Project structure:"
        tree -a || true

    - name: Setup Gradle
      run: |
        # 检查现有的Gradle文件
        if [ -f "build.gradle" ]; then
          echo "Using existing build.gradle"
          cat build.gradle
        fi
        
        if [ -f "settings.gradle" ]; then
          echo "Using existing settings.gradle"
          cat settings.gradle
        fi
        
        if [ -f "gradle.properties" ]; then
          echo "Using existing gradle.properties"
          cat gradle.properties
        fi
        
        # 如果没有gradle wrapper，创建一个
        if [ ! -f "gradlew" ]; then
          echo "Creating Gradle Wrapper..."
          gradle init --type basic --dsl groovy --project-name AIDE-Plus
          gradle wrapper --gradle-version 7.3.3
          chmod +x gradlew
        fi
        
        echo "Project structure after setup:"
        ls -la
        echo "Available Gradle tasks:"
        ./gradlew tasks --warning-mode all || true

    - name: Build Project
      run: |
        echo "Starting build process..."
        # 尝试直接构建
        ./gradlew build --warning-mode all --info --stacktrace || true
        
        # 如果直接构建失败，尝试特定模块
        if [ -f "app/build.gradle" ]; then
          echo "Building app module..."
          ./gradlew :app:assembleDebug --warning-mode all --info --stacktrace || true
        fi
        
        if [ -f "app_rewrite/build.gradle" ]; then
          echo "Building app_rewrite module..."
          ./gradlew :app_rewrite:assembleDebug --warning-mode all --info --stacktrace || true
        fi
      
    - name: Run Tests
      if: always()
      continue-on-error: true
      run: |
        echo "Running tests..."
        ./gradlew test --warning-mode all --info || true
      
    - name: Build Native Libraries
      if: always()
      continue-on-error: true
      run: |
        if [ -d "native/EnsureCapacity" ]; then
          cd native/EnsureCapacity
          cmake .
          make
        fi
        
    - name: Upload APK
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: |
          */build/outputs/apk/debug/*.apk
        if-no-files-found: warn
        
    - name: Upload Native Libraries
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: native-libs
        path: |
          */build/**/*.so
        if-no-files-found: warn

    - name: Upload Build Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          */build/reports/**/*
          build/reports/**/*
        if-no-files-found: warn
